spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestion_de_supermarche?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Gmci@2001
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: mysql
    show-sql: false
    properties:
      hibernate:
        session_factory:
          interceptor: com.GBG.gestiondesupermarche.interceptor.Interceptor

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081

#its information about the flickr api "photos"
flickr:
  apiKey: 8cb125aa193363faf29c79c5b4e4cdda
  apiSecret: 7d8094520a278763
  appKey: 72157720877815072-7c1751960e18f3a6
  appSecret: 7ee275ba806ba7df

